### ISSUE TITLE
cartesian sample set not handling 1-D data space

### ISSUE THREAD

**Issue by eecsu** [UT-CHG/BET#277]
With a data space that is 1-D, I am getting errors in the linear and nonlinear examples 

Traceback (most recent call last):
  File "nonlinearMapUniformSampling.py", line 124, in <module>
    cells_per_dimension = 3)
  File "build/bdist.linux-x86_64/egg/bet/calculateP/simpleFunP.py", line 457, in regular_partition_uniform_distribution_rectangle_scaled
  File "build/bdist.linux-x86_64/egg/bet/calculateP/simpleFunP.py", line 363, in regular_partition_uniform_distribution_rectangle_size
  File "build/bdist.linux-x86_64/egg/bet/sample.py", line 2057, in setup
  File "build/bdist.linux-x86_64/egg/bet/sample.py", line 1693, in setup
bet.sample.length_not_matching: Rectangle 0 has the wrong number of entries.

The above is for the nonlinear example. I get the same error in the same places if I switch the model in the linear example to be just a single QoI instead of a 2D map.

**Comment by eecsu** [comment]
I think switching lines 2047 and 2048 of sample.py to 

            maxes = np.transpose(np.array([xmax]))
            mins = np.transpose(np.array([xmin]))

fixes this bug. Is this going to have any unintended consequences?

**Comment by eecsu** [comment]
I think I have this fixed now. I will submit a pull request.
